name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add project root to PYTHONPATH
      run: |
        export PYTHONPATH="${PYTHONPATH}:/home/runner/work/Lab1/Lab1"
        echo "PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV

    - name: Run tests
      run: pytest
